[google_auth]
client_id = "564190080993jb609vu90nr4h4ppbgs4rdbr882sg362.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://simuladorbcmed.streamlit.app/"
